### ISSUE TITLE
Feature Request: Allow user to create Journal Entries in the Journal instead of Compendium

### ISSUE THREAD

**Issue by mdiviesti** [Ethck/azgaar-foundry#35]
While a character might have knowledge of their continent, they may not have knowledge of smaller bergs. 
In order to facilitate this in game, the permissions system could be used, effectively hiding a berg until your players stumble on it and get to know the place a bit. This is not possible when all entries are in the compendium. 
Which version of import a DM wants to use should be configurable.

**Comment by Ethck** [comment]
You can change the default permissions when importing the map and then manually change the permissions when your players have found a new burg. The primary reason that the journals exist in the compendium is due to the fact that Foundry doesn't load content from Compendiums until called upon. This saves a significant amount of resources when loading since Foundry won't have to load hundreds, possibly thousand+, journals every time you load into the world for the first time.
